Denarios/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import include


urlpatterns = [
    path('', include('app.urls', namespace='app')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('analisis/', views.analisis, name='analisis'),  # No date parameters
    path('analisis/mensual/<str:year>/<str:month>/', views.analisis, name='analisis_mensual'),
    path('analisis/anual/<str:year>', views.analisis, name='analisis_anual'),
    path('analisis/<str:year>/<str:symbol>', views.analisis, name='analisis_symbol'),  # No date parameters
    path('analisis/<str:year>/<str:month>/<str:symbol>', views.analisis, name='analisis_symbol_mensual'),
    # path('analisis/<str:start_date>/<str:end_date>/', views.analisis, name='analisis_with_dates'),
    # With date parameters
]

app/templates/analisis.html
{% extends 'base.html' %}
{% block title %}Analisis{% endblock %}
{% block content %}
    <br>
    <div class="row mx-auto justify-content-center mb-12">
      <div class="float-left btn-group flex-wrap col-xl-6 col-lg-7 col-md-9 col-sm-12 col-12 h-50">
           <a {% if year == '2022' %} class="btn btn-info active" {% else %}class="btn btn-info" href="{% url 'app:analisis_anual' '2022' %}"{% endif %}>2022</a>
           <a {% if year == '2023' %} class="btn btn-info active" {% else %}class="btn btn-info" href="{% url 'app:analisis_anual' '2023'  %}"{% endif %}>2023</a>
      </div>
    </div><br>
    <br>
    <br>
    <div class="row mx-auto justify-content-center mb-12">
        <div class="float-left btn-group flex-wrap col-xl-6 col-lg-7 col-md-9 col-sm-12 col-12 h-50">
        {% for month_number, month_name in month_choices %}
            {% if symbol %}
                <a class="btn btn-info{% if month == month_number %} active{% endif %}" href="{% url 'app:analisis_symbol_mensual' year month_number symbol %}">{{ month_name }}</a>
            {% else  %}
                <a class="btn btn-info{% if month == month_number %} active{% endif %}" href="{% url 'app:analisis_mensual' year month_number %}">{{ month_name }}</a>
            {% endif %}
        {% endfor %}
        </div>
    </div><br>
    <br>
   <div class="row text-white">
          <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 mx-auto text-center form p-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="table-wrapper-scroll-y my-custom-scrollbar">
                            <table class="table table-striped table-light table-hover table-bordered mb-0" style="line-height: 0.6">
                                <thead class="thead-dark sticky-top">
                                    <tr>
                                        <th><a class="text-truncate text-light" >Coin</a></th>
                                        <th><a class="text-truncate text-light" >Type</a></th>
                                        <th><a class="text-truncate text-light" >Simulation</a></th>
                                        <th><a class="text-truncate text-light" >ratio</a></th>
                                        <th><a class="text-truncate text-light" >sl limit</a></th>
                                        <th><a class="text-truncate text-light" >sl low limit</a></th>
                                        <th><a class="text-truncate text-light" >rsi op</a></th>
                                        <th><a class="text-truncate text-light" >stochastic</a></th>
                                        <th><a class="text-truncate text-light" >PnL</a></th>
                                        <th><a class="text-truncate text-light" >Duration</a></th>
                                        <th><a class="text-truncate text-light" >Positions</a></th>
                                        <th><a class="text-truncate text-light" >TP</a></th>
                                        <th><a class="text-truncate text-light" >SL</a></th>
{#                                        <th><a class="text-truncate text-light" >TPrsi</a></th>#}
{#                                        <th><a class="text-truncate text-light" >SLrsi</a></th>#}
                                        <th><a class="text-truncate text-light" >Av PnL</a></th>
                                        <th><a class="text-truncate text-light" >Fee Total</a></th>
                                        <th><a class="text-truncate text-light" >Max PnL</a></th>
                                        <th><a class="text-truncate text-light" >Min PnL</a></th>
                                        <th><a class="text-truncate text-light" >Avg TP</a></th>
                                        <th><a class="text-truncate text-light" >Avg SL</a></th>
                                    </tr>
                                </thead>

                                <tbody id="myTable">
                                    {% for r in lista %}
                                        <tr>
                                            <td>
{#                                                <a href="{% url 'app:analisis_symbol' year r.symbol__symbol %}" class="text-truncate text-dark align-middle" >{{ r.symbol__symbol }}</a>#}
                                            </td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.type }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.simulation }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.tp_sl_ratio }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.sl_limit }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.sl_low_limit }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.rsi_open }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.stoch_open }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.pnl_total|floatformat:2 }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.avg_duration }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.positions }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.TP }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.SL }}</a></td>
{#                                            <td><a class="text-truncate text-dark align-middle" >{{ r.TPrsi }}</a></td>#}
{#                                            <td><a class="text-truncate text-dark align-middle" >{{ r.SLrsi }}</a></td>#}
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.pnl_average|floatformat:3 }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.total_fee|floatformat:2 }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.max_pnl|floatformat:2 }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.min_pnl|floatformat:2 }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.avg_pnl_tp|floatformat:2 }}</a></td>
                                            <td><a class="text-truncate text-dark align-middle" >{{ r.avg_pnl_sl|floatformat:2 }}</a></td>

                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
          </div>
   </div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Next level Investments">
    <meta name="keywords" content="Invesments">
    <meta name="copyright" content="Martin Moran Goycoolea">
    <meta name="author" content="Martin Moran Goycoolea">
<!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-172323238-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-172323238-1');
    </script>

    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="shortcut icon" href="{% static ''%}" type='image/x-icon'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
    <script src = {% static 'js.js' %}> </script>
    <title>{% block title %}Denarios{% endblock %}</title>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">


    {% block head %}

    {% endblock %}
</head>

{###background-color:#1f1f1f;  oscuro#}
<body {% block bodytype %} style="background-color:#7c7c7c;"{% endblock %}>
<div id="page-container">
  <div class="content-wrap">
    <header class="site-header">
        <!-- expand md esra que se oculten los botones cuando la pantalla es medium se puede cambiar a sm lg ets-->
        <nav class="navbar navbar-expand-xl bg-dark navbar-dark border border-top-0 border-right-0 border-left-0 border-info">
         <!-- container fluid usa toda la pantalla  solo container queda en el medio-->
            <div class="container-fluid">
                <img class="navbar-brand" alt="Paralegapp logo" src="{% static 'images/logo1.png' %}" width="130px">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {% if user.is_authenticated %}
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link text-light" href="">
                                <span class="fas fa-home text-truncate" aria-hidden="true">&nbsp Inicio</span>
                            </a>
                            <a class="nav-item nav-link text-light" href="">
                                <span class="fas fa-briefcase text-truncate" aria-hidden="true">&nbsp Portfolio</span>
                            </a>
{#                            <a class="nav-item nav-link text-light" href="">#}
{#                                <span class="fas fa-bell text-truncate" aria-hidden="true">&nbsp Novedades </span>#}
{#                            </a>#}
{#                            <a class="nav-item nav-link text-light" href="{% url 'paralegapp:mis_estados' '-fecha_ingreso' 1 %}">#}
{#                                <span class="fas fa-history text-truncate" aria-hidden="true">&nbsp Historias </span>#}
{#                            </a>#}
{#                            <a class="nav-item nav-link text-light" href="">#}
{#                                <span class="fas fa-tasks text-truncate" aria-hidden="true">&nbsp Tareas </span>#}
{#                            </a>#}
{#                            <a class="nav-item nav-link text-light" href="">#}
{#                                <span class="fas fa-plus text-truncate" aria-hidden="true">&nbsp Agregar Causas</span>#}
{#                            </a>#}
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            <!--a class="nav-item nav-link text-light" href="{ # url 'paralegapp:gestion' %}">
                                <span class="fas fa-chart-bar text-truncate" aria-hidden="true"> &nbspGestión</span>
                            </a-->
                            <a class="nav-item nav-link text-light" href="">
                                <span class="fas fa-user text-truncate" aria-hidden="true"> &nbsp{{ user.first_name }} </span>
                            </a>
                            <a class="nav-item nav-link text-light" href="">
                                <span class="fas fa-question-circle text-truncate" aria-hidden="true"> &nbspAyuda</span>
                            </a>
                            <a class="nav-item nav-link text-light" href="">
                                <span class="fas fa-sign-out-alt text-truncate" aria-hidden="true">&nbsp Salir</span>
                            </a>
                        </div>
                    </div>
                {% else %}
                     <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link" href="">
                                <span aria-hidden="true"></span> Inicio &nbsp
                            </a>
                            <a class="nav-item nav-link" href="">
                                <span aria-hidden="true"></span>Como funciona
                            </a>
                        </div>
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav">
                            <a class="nav-item nav-link" href="">
                                <span  aria-hidden="true"></span> LogIn
                            </a>
                            <a class="nav-item nav-link" href="">
                                <span aria-hidden="true"></span> Crear Cuenta
                            </a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </nav>
    </header>

    <main role="main" class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                           {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}

                {% block content %}



                {% endblock %}

            </div>
        </div>
    </main>
  <div id="extraspace">
  </div>
  </div>
    <footer>
        <div class="footer" id="footer">
             <!-- expand md esra que se oculten los botones cuando la pantalla es medium se puede cambiar a sm lg ets-->
            <nav class="navbar navbar-expand-sm bg-dark navbar-dark" style="height: 2.5rem">
             <!-- container fluid usa toda la pantalla  solo container queda en el medio-->
                 <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link text-light">
                            <span  aria-hidden="true"></span>
                        </a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav text-white">
                        <span class="fab fa-whatsapp text-truncate" aria-hidden="true"></span>&nbsp&nbsp
                    </div>
                 </div>
            </nav>
        </div>
    </footer>
</div>
    <script src="{% static 'js.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>